name: SizCraftCore
version: '${project.version}'
main: com.sizcraft.sizcraftcore.SizCraftCore
api-version: 1.19
authors: [ SizGen ]
description: The core of the sizcraft network
website: www.sizcraft.nl
